### ISSUE TITLE
Floating compose panel

### ISSUE THREAD

**Issue by passcod** [eramdam/BetterTweetDeck#256]
From #255:

Instead of having the compose panel push the columns to the right, it appears "on top" of the rest of the view, so the display doesn't move. It also makes it faster (less animation / rendering!). I added some shadows to make it clear that it's above.

This was my implementation, for reference:

```css
    .app-content.is-open .drawer[data-drawer=compose] {
        box-shadow: 3px 3px 3px 0px rgba(0, 0, 0, 0.2);
        left: 0;
        z-index: 999;
    }

    .app-content.is-open {
        transform: none !important;
        margin-right: 0 !important;
    }
```

![screenshot from 2017-10-27 11-17-36](https://user-images.githubusercontent.com/155787/32079736-75d9cab6-bb08-11e7-88d6-c900b196f9d0.png)
