### ISSUE TITLE
Floating rolled-up column headers

### ISSUE THREAD

**Issue by passcod** [eramdam/BetterTweetDeck#257]
From #255:

A bit of an odd one. Basically, the headers are collapsed "upwards", then a gutter is revealed on column hover, and then the entire header is revealed on hover of that gutter. The goal is to hide the header chrome until it's needed.

There might more interesting ways to do this / add to this when more than just CSS is available. Off the top of my head:
- Add an indicator to the gutter when there's an update in this column (i.e. when the header text would normally be blue)
- Change the colour of the gutter based on idk, something. Maybe just a different colour from the rainbow per column?
- etc

It looks and behaves like this:

![peek 2017-10-27 10-48](https://user-images.githubusercontent.com/155787/32078783-b6f29018-bb04-11e7-8e85-512448041cdf.gif)

<sup>(The column contents jumping up a bit on hover is a bug and not intentional.)</sub>

My implementation:

```css
    .column-header {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 0px;
        transition: height 100ms;
        z-index: 100;
        overflow: hidden;
        background: white !important;
    }
    .column:hover .column-header {
        height: 12px;
        box-shadow: 0 0 0.5em 0 rgba(0, 0, 0, 0.2);
        border-bottom: 1px solid lightgray;
    }
    .column-header:hover {
        height: 50px !important;
    }
```
