### ISSUE TITLE
Incorrect needs-scroll-bottom-offset

### ISSUE THREAD

**Issue by xPaw** [eramdam/BetterTweetDeck#317]
I'm not sure why TweetDeck inserts this, but this causes a white line (which is from account selector) to show up under columns.

This is the style that is causing this:
```css
html.dark .needs-scroll-bottom-offset.scroll-styled-h {
	bottom: 4px;
}
```

which looks like that:
![03-085048046](https://user-images.githubusercontent.com/613331/35765601-155f7922-08d0-11e8-8412-36b5cea3c594.png)

Resetting `bottom` to `0` fixes that. Enabling thinner scrollbars also fixes that, so there's that.

Is this something that can be fixed in BTW or has to be raised with Twitter themselves (not sure how to get hold of them though).
