### ISSUE TITLE
Multi-row layout

### ISSUE THREAD

**Issue by munierujp** [eramdam/BetterTweetDeck#377]
I'd like to show more rows to see more information without horizontal scrolling.

## Image
![fullsizeoutput_ce3](https://user-images.githubusercontent.com/20086673/44310119-04afe800-a40c-11e8-8365-ee8dfb875bf5.jpeg)

## Sample implementation
2 row layout:

```css
.app-columns {
    display: flex;
    flex-direction: column;
    flex-wrap: wrap;
}

.is-wide-columns .column {
    height: calc(100vh / 2);
}
```
