### ISSUE TITLE
[Feature] Tweet/RTs Color Line by User

### ISSUE THREAD

**Issue by LukasThyWalls** [eramdam/BetterTweetDeck#391]
Something Twidere (and i think others clients too) and maybe on Tweetdeck can be useful.

By user (as an option in every user's profile) you can choose a color to highlight tweets, RTs and responses from that user. The tweet is not entirely of that color, maybe can be only a line in the left side like Twidere:

![twidereusercolors](https://user-images.githubusercontent.com/1467366/50174853-987ebb80-02fb-11e9-957f-ab105f0fad0c.jpg)

This can make more easy to spot some accounts above others (with RTs, choosing the same color for a bunch of users by topic, etc.)

**Comment by eramdam** [comment]
Hum, I do like the idea but I'm afraid having a colored line on tweets on multiple columns might be very overwhelming visually. Besides, if you don't want to miss one's tweets you can just... have a column with only their tweets? 😅 

Perhaps I'm missing something?

**Comment by LukasThyWalls** [comment]
If it is not so intrusive (like Twidere does, with only a line), it's not like a "rainbow" everywhere.

I use this in Twidere to highlight some people tweets: For example, all people from a website have red color, other people from a website community are grey, a friend has green, other one is pink... and if you see a tweet or a retweet (also made by them, not only from one of their tweets) you can spot easily over the other tweets in every column (normally Home, but in Notifications, Likes or a search too).

That's why i asked to add this to Tweetdeck (if it's possible) because i see it useful.

> if you don't want to miss one's tweets you can just... have a column with only their tweets?

It's not about not to miss any tweet... is about spot tweets easily from selected sources (user or group of users) in Home, Notifications, etc...

**Comment by eramdam** [comment]
I don't really have time to make this into an actual feature, but you can hack something together with custom CSS.

```css
.stream-item .tweet-header a.account-link[href*='/TwitterUsername']::after {
  content: '';
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  box-shadow: inset 2px 0 red;
}
```
![image](https://user-images.githubusercontent.com/1409924/108016270-f801b000-6fc6-11eb-8bb4-7b343c5cad51.png)

**Comment by LukasThyWalls** [comment]
Thanks to ponder this.

Seeing this in action adding that CSS convinces me more it's still a good idea, i will try to use it like this. However i understand your point. Maybe some day can be done. Thanks.

**Comment by LukasThyWalls** [comment]
Sadly, the css code interferes with clicking tweets with colors (it opens the user card always), so i need to disable it.

**Comment by eramdam** [comment]
> Sadly, the css code interferes with clicking tweets with colors (it opens the user card always), so i need to disable it.

Ah, indeed. I forgot to include `pointer-events: none`

```css
.stream-item .tweet-header a.account-link[href*='/TwitterUsername']::after {
  content: '';
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  box-shadow: inset 2px 0 red;
pointer-events: none;
}
```

Shouldn't interefer with clicks anymore
