### ISSUE TITLE
Options to hide and shrink avatars

### ISSUE THREAD

**Issue by roycewilliams** [eramdam/BetterTweetDeck#413]
This is a feature request to allow hiding and shrinking of avatars. The presence of the avatar eats a significant percentage of each column.

A significant amount of whitespace could be reclaimed. That space could be used to display text instead, or to allow smaller columns and higher column density.

Once you see it, you can't unsee it. :)

**Comment by roycewilliams** [comment]
It occurs to me that allowing the user to _change_ the avatar size might be more flexible. You could just set it to zero to address my specific use case. :)

**Comment by roycewilliams** [comment]
Apologies for not knowing enough CSS to be able to implement this as custom CSS instead!

**Comment by eramdam** [comment]
This is a crude workaround but this bit of CSS hides the space taken by avatars in the columns 

```css
.tweet {
  padding-left: 6px !important;
}

.tweet-context .obj-left {
    width: 60px !important;
}

.activity-header .item-img {
    width: auto !important;
}

.tweet .obj-left .tweet-avatar,
.activity-header.has-source-avatar .avatar {
    display: none !important;
}
```

![Screen Shot 2021-06-17 at 10 44 09 PM](https://user-images.githubusercontent.com/1409924/122512352-9590de80-cfbd-11eb-9221-2ca5410ee592.png)
