### ISSUE TITLE
Dark theme dropdown is difficult to read when using 'Revert Dark Theme' CSS

### ISSUE THREAD

**Issue by EvilJackCarver** [eramdam/BetterTweetDeck#433]
The dropdown menus on tweets are very difficult to read when using night-mode with the 'revert dark theme' CSS tweak. The `color` key in revert-dark-theme.css is set to `#292F33`. 

![image](https://user-images.githubusercontent.com/1784490/62415036-4cae2780-b5e9-11e9-9e22-c825e6f34d36.png)

I was able to correct this (temporarily) by going into the element inspector and editing `html.dark .dropdown-menu a:not(:hover):not(:focus)` to `#fff` (the element inspector says that's line 517 of revert-dark-theme.css). However, I'm not proficient enough in CSS to be confident in putting that tweak in my Custom CSS slot.

The text is legible when highlighted.

![image](https://user-images.githubusercontent.com/1784490/62415049-6bacb980-b5e9-11e9-8014-ddb46be65c7a.png)

**Comment by tdeary** [comment]
Also having this bug. Editing the CSS in the inspector temporarily fixes it as @EvilJackCarver said, but putting the same snippet into the custom CSS does nothing. I tried editing other things in the custom CSS too and it seems like the dark revert stylesheet might be overwriting the changes in custom CSS.

**Comment by ping** [comment]
I was able to fix this for myself with the snippet below in custom css. Tested on FireFox.

```css
/* fix text color */
htm.dark .dropdown-menu .non-selectable-item
, html.dark .dropdown-menu .js-dropdown-content a:not(:hover):not(:focus)
, html.dark .dropdown-menu .js-dropdown-content .non-selectable-item { color: #e1e8ed; }
/* fix background color */
html.dark .dropdown-menu { background-color: #292F33; }
```
