### ISSUE TITLE
[Feature Request]  Add column size for Compose window

### ISSUE THREAD

**Issue by damianrath** [eramdam/BetterTweetDeck#456]
Please add a interface option so we easily, without custom CSS, can alter the slide-out Compose column's horizontal size.

I would also like to take the time to thank you for a great addon to Tweetdeck. Much appreciated.

**Comment by eramdam** [comment]
Might be useful indeed. I'll think about it.

In the meantime you might get away by using the Custom CSS option and putting this:
```css
.js-drawer.drawer {
width: <width>px !important;
}

.js-app-content.app-content.is-open {
transform: translateX(<width>xp) !important;
}
```

Note that the compose panel is using the same component as the account settings so you'd need to change the width of that + some UI elements might looks weird/not display properly because of the changed width.

**Comment by damianrath** [comment]
Thank you for the consideration. However, the above custom CSS code only changes the width of the elements within the fly-out JS drawer, but the drawer itself is (read: width of that column) is still the same.

I will just wait and hope you will it in your heart to add a proper feature for it.

**Comment by eramdam** [comment]
Indeed, I did a mistake in the code. Here's a fixed version
```css
:root {
    --custom-drawer-width: 600px; /* change this value */
}

.js-drawer.drawer {
    width: var(--custom-drawer-width) !important;
    left: calc(var(--custom-drawer-width) * -1) !important;
}

.js-app-content.app-content.is-open {
    transform: translateX(var(--custom-drawer-width)) !important;
}
```
