### ISSUE TITLE
[Feature Request] Square corners medium sized media

### ISSUE THREAD

**Issue by Haatmeneer** [eramdam/BetterTweetDeck#528]
I know the large media option hides the rounded corners. But is it possible to remove the rounded corners from the medium sized media? Maybe in css?

**Comment by eramdam** [comment]
You should be able to achieve this with this bit of custom CSS

```css
.media-size-medium {
border-radius: 0 !important;
}
```
