### ISSUE TITLE
Allow any color for accent

### ISSUE THREAD

**Issue by nymphlode** [eramdam/BetterTweetDeck#539]
I'd like to be able to utilize a color picker to choose an accent color, as I'd like purple but the purple provided by the extension hurts my eyes trying to read.

**Comment by eramdam** [comment]
I'll try to figure something out in the future, in the meantime you can set any accent color and use the following custom CSS snippet to put whatever you want:

```css
body {
  --btd-accent-color: pink !important;
}
```

(Obviously replace `pink` with your color 😁 )
