### ISSUE TITLE
⚠️ About CSS tweaks ⚠️ 

### ISSUE THREAD

**Issue by eramdam** [eramdam/BetterTweetDeck#546]
Before opening an issue about adding a feature to tweak the style of TweetDeck, please check out the [Custom CSS snippets](https://github.com/eramdam/BetterTweetDeck/wiki/Custom-CSS-recipes) page in the wiki. 

If something is missing and you think should be there, comment in this thread and we'll figure something out and add a snippet to that page so it's more visible.

**Comment by unbekannt3DE** [comment]
I'm using the old gray theme and added some margin to the Home, Activity, ... columns for better visual distinction between these:
![image](https://user-images.githubusercontent.com/10979501/113635585-32a3d280-9671-11eb-85c9-cfc503f7b8dd.png)

```css
section {
    margin-left: .2em !important;
}

section:first-child {
    margin-left: .25em !important;
}
```

There is probably a better solution then adding this directly to a section but it didn't break anything for me atm...

**Comment by Commenter25** [comment]
Two very quick and dirty changes to Super Dark mode. Only tested in Firefox. Needs changing to apply only to Super Dark, but they look far more consistent.

First one recolors the separation between column items so it still appears.
```css
html.dark .stream-item {
    border-bottom: 1px solid #222;
}
```

Second one recolors the scrollbar to be greyscale and fit with the rest of the theme. scrollbar-color is unfortunately something only Firefox has for now. There were some Internet Explorer specific properties too, but, well... kinda hard for a Linux user to test that :p
```css
html.dark .scroll-styled-h, html.dark .scroll-styled-v {
    scrollbar-color: #333 #000;
}
```

**Comment by JaxxArmstrong** [comment]
May I humbly recommend that _!important_ is added to the two snippets that doesn't contain them at the _Custom CSS Snippets_ page.

It might cut down on questions why they won't work etc, if that comes up.

**Comment by alefnull** [comment]
i liked the snipped that automatically hides/reveals column titles when they're hovered over, but i wanted it to happen when i hover over the entire column, not just the header itself, so i added the small bit below, and now the headers open and close when i move my mouse anywhere over their column.

```css
/* ========== hide column headers until hovering over them ========== */
.column:hover .column-header {
  height: 50px !important;
}
```

also, i can't currently remember where i found this snippet, but it makes the compose panel float above columns when opened, instead of pushing them all to the right.

```css
/* ========== floating compose panel ========== */
.app-content.is-open .drawer[data-drawer="compose"] {
  box-shadow: 3px 3px 3px 0px rgba(0, 0, 0, 0.2);
  left: 0;
  z-index: 999;
}
.app-content.is-open {
  transform: none !important;
  margin-right: 0 !important;
}
```

**Comment by Arkhorse** [comment]
These css code snipets are what I use:
Allow resizing the compose box vertically:
```css
html.dark .compose-text {
    width:100%;
    height:250px;
    resize:vertical;
    border:none;
    color:#fff!important;
}
```

Fix dark mode so there is no glaring white boxes:
```css
html.dark .Button,html.dark .Button.is-visited,html.dark .Button:visited,html.dark button,html.dark button.is-visited,html.dark button:visited,html.dark input.is-visited[type="button"],html.dark 
input:visited[type="button"],html.dark input[type="button"]{display:inline-block;position:relative;padding:6px 14px;background-color:#3d5466!important;border:1px solid #3d5466!important;border-radius:36px;color:#fff!important;cursor:pointer;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-size:14px;font-weight:700;line-height:22px;}
html.dark .compose-text-container{background-color:#3d5466!important;}
html.dark .quoted-tweet{border:1px solid #e1e8ed;color:#fff!important;font-size:0.9em;border-color:black;color:#fff!important;}
html.dark .bg-color-twitter-white{background-color:#3d5466!important;}
.mdl{display:inline-block;vertical-align:middle;position:relative;width:643px;height:630px;margin:0 auto;background-color:black!important;text-align:left;border-radius:14px;box-shadow:0 0 10px rgba(20, 23, 26, 0.5);}
.mdl-accent{background:black!important;}
.mdl-header-divider{border-bottom:1px solid black!important;}
```

Botsentinel code for the above dark mode changes:
```css
/* Bot Sentinel */
.bot-sentinel-account-status .rating-card.Unknown{background:#3d5466!important;}
.bot-sentinel-account-status .rating-card.Normal{background:#10610E!important;}
.bot-sentinel-modal .modal-content{min-height:470px;width:475px;right:50%;top:50%;transform:translate(50%, -50%);position:absolute;overflow:visible;box-shadow:grey 0px 0px 7px;background:black!important;border-width:0px;border-style:initial;border-color:initial;border-image:initial;border-radius:3px;}
```

I hope some of this is useful. And that some of it gets implemented (the dark mode fixes pls)

**Comment by FiascoBadmandry** [comment]
Hi there, Great work on BTDi'd like to contribue with this css bits I use to customize accent color and make sure it's applied to all colored stuff (column glow, new tweets in column indicator, etc...) : 
`body{
    --btd-accent-color: rgb(183, 200, 85) !important;
}

html.dark .is-new .column-type-icon {
    color:var(--btd-accent-color) ;
}
html.dark .column-nav-updates {
    color:var(--btd-accent-color);
}
.js-more-tweets-glow{
   background: radial-gradient(ellipse farthest-corner at 50% 100%,var(--btd-accent-color), var(--btd-accent-color),hsla(0,0%,100%,0) 75%) !important;
    background-color: rgba(0, 0, 0, 0) !important;
    background-position-x: 0% !important;
    background-position-y: 0% !important;
    background-repeat: repeat!important;
    background-attachment: scroll!important;
    background-image: radial-gradient(at 50% 100%,var(--btd-accent-color) 0px, var(--btd-accent-color) 25%, rgba(255, 255, 255, 0) 75%)!important;
    background-size: auto!important;
    background-origin: padding-box!important;
    background-clip: border-box!important;
}`
Hope this helps, keep up the good work!

**Comment by mediocrenoob** [comment]
Not mine but I've been using it since it was originally posted on Stylish repo. It makes the columns flexible.

```
#container > div.app-columns {
     display: flex;
}
 #container > div.app-columns > .column {
     flex: 1;
     min-width: 350px;
}
```

[Original style](https://uso.kkx.one/style/127675)

**Comment by Grimtendo** [comment]
I've tried
`.js-column.column:nth-child(1) {
  width: 500px;
}`
and 
`#container > div.app-columns {
     display: flex;
}
 #container > div.app-columns > .column {
     flex: 1;
     min-width: 350px;
}`
so I can customize different column sizes, but neither seem to change anything. Am I missing something?

**Comment by anatawa12** [comment]
The style to place columns from right to left.
I put a sub-display on left and show TweetDeck on the sub-display so I wanted to place columns from right to left so I made this.

```css
.js-app-columns-container.app-columns-container {
    direction: rtl;
}

.js-app-columns.app-columns>* {
    direction: ltr;
}
```

**Comment by Mathinios** [comment]
> Not mine but I've been using it since it was originally posted on Stylish repo. It makes the columns flexible.
> 
> ```
> #container > div.app-columns {
>      display: flex;
> }
>  #container > div.app-columns > .column {
>      flex: 1;
>      min-width: 350px;
> }
> ```
> 
> [Original style](https://uso.kkx.one/style/127675)

And like this ?

> root {
>    --custom-drawer-width: 270px; /* change this value */
>}
>
>.js-drawer.drawer {
>    width: var(--custom-drawer-width) !important;
>    left: calc(var(--custom-drawer-width) * -1) !important;
>}
>
>.js-app-content.app-content.is-open {
>    transform: translateX(var(--custom-drawer-width)) !important;
>}.js-column.column:nth-child(1) {
>  width: 400px;
>}.js-app-content.app-content.is-open {
>    transform: translateX(var(--custom-drawer-width)) !important;
>}.js-column.column:nth-child(2) {
>  width: 300px;
>}#container > div.app-columns {
>     display: flex;
>}
> #container > div.app-columns > .column {
>     flex: 1;
>     min-width: 350px;
>}

**Comment by Arkhorse** [comment]
If you want to make the gif panel larger, this is the code to do it. Just dont increase the height, as this seems to be the max (1920x1080)
```css
.btd-giphy-1x4vipd {
    width: 750px;
    height: 750px;
}
```

**Comment by Lu9-ST** [comment]
Code that might be useful for a couple people with many accounts connected on TD: 
After a certain point in time, Twitter updated its Privacy Policy and made sure that it won't shut up about it until every connected account has accepted it - I have a couple accounts I can still access through tweetdeck, but essentially, I can't login to them normally anymore, so I cannot simply log in to "accept" the new terms, therefore I'm stuck forever with the message on top of the screen (which you can't hide)

So here is a very simple thing that does just that (although it might also hide OTHER warnings that can show up, but that is probably not a big problem either)

`.js-message-banner {
    display: none;
}`

**Comment by alexbcberio** [comment]
Tweaks I have and might be helpful for yourself

1. Increase the contrast of the focused container background when navigating with the keyboard (hjkl keys or arrows) on "super-dark" theme
	```css
	html.dark body[btd-theme='super-dark'] {
	    --btd-theme-background-lighter: hsl(0deg 0% 15%);
	}
	```
2. Add a separator to the columns, using the user configured color
	```css
		.js-app-columns .column {
	    box-sizing: border-box;
	    border-right: 2px solid var(--btd-accent-color);
	}
	```
3. Make the last column icon of the vertical header reachable
	```css
	#column-navigator ul {
	    padding-bottom: 37px;
	}
	```
4. Credits to @anatawa12 for the basis on this one. Make the columns responsive and adapt its sizes based on the browser window width, making all the columns fit almost perfectly the whole width.
	```css
	  #container > div.app-columns {
	      --num-columns: 1;
	      display: flex;
	  }
	  
	  #container > div.app-columns > .column {
	      flex: 1;
	      min-width: calc((100vw - 60px) / var(--num-columns));
	  }
	  
	  @media screen and (min-width: 750px) {
	      #container > div.app-columns {
	          --num-columns: 2;
	      }
	  }
	  
	  @media screen and (min-width: 1000px) {
	      #container > div.app-columns {
	          --num-columns: 3;
	      }
	  }
	  
	  @media screen and (min-width: 1300px) {
	      #container > div.app-columns {
	          --num-columns: 4;
	      }
	  }
	  
	  @media screen and (min-width: 1550px) {
	      #container > div.app-columns {
	          --num-columns: 5;
	      }
	  }
	  
	  @media screen and (min-width: 1800px) {
	      #container > div.app-columns {
	          --num-columns: 6;
	      }
	  }
	```
