### ISSUE TITLE
Comments are not preserved or not synced in the custom css section?

### ISSUE THREAD

**Issue by passcod** [eramdam/BetterTweetDeck#566]
**Describe the bug**

I was pleasantly surprised to see custom css was synced (granted I'd never used the feature before, so I don't know if that was a thing already). However, I'd inputted some comments along with my tweaks, to document what each was about. On my other computer, the comments were not there.

**To Reproduce**

1. Add some custom css, e.g.
   ```css
   /* test */
   a {
     color: red;
   }
   ```
2. go to firefox on other device and force a sync
3. open BTD settings on that device
4. custom css will read:
   ```css
   a {
     color: red;
   }
   ```

**Expected behavior**

For the exact content to be synced, or at least for comments to be preserved.

---

    Version: 4.0.0
    User agent: Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
