### ISSUE TITLE
Allow disabling emoji picker button

### ISSUE THREAD

**Issue by xPaw** [eramdam/BetterTweetDeck#569]
![image](https://user-images.githubusercontent.com/613331/113854552-a811bf00-97a7-11eb-8c05-6610a4b1064c.png)

It takes up space in the composer, and I prefer using OS picker (win+.) anyway.

**Comment by eramdam** [comment]
I might add a setting if enough people request it, in the meantime, you can use this piece of Custom CSS

```css
#emojiButton {
    display: none !important;
}

.js-drawer .js-compose-text {
    width: 100% !important;
}
```
