### ISSUE TITLE
Viewing an image is the same whether "fullscreen" option set or not, except for image display size

### ISSUE THREAD

**Issue by AbuMaia** [eramdam/BetterTweetDeck#579]
Gone apparently is the "window" that would pop up when you click on an image to view it. Now, whether the "Display fullscreen images à la Twitter Web" option is selected or not, the entire screen dims and the image is shown in the middle. The only difference is when the option is disabled, the displayed image is smaller than when the option is enabled.
Can we not get the old "window" back?

**Comment by eramdam** [comment]
> The only difference is when the option is disabled, the displayed image is smaller than when the option is enabled.

That's not actually true. Now by default you can dismiss the fullscreen view by clicking outside of the image, whereas on vanilla TweetDeck you'd have to click outside of the (huge) zone containing the image. I think this is more convenient and looks more modern overall, unless you have a very good reason I don't see why you'd want the old style back, to be frank.

**Comment by AbuMaia** [comment]
Holy shit, that's probably the rudest dev I've ever encountered.

**Comment by eramdam** [comment]
You're right. My answer was rude, I'm sorry about that. Long week and I took it out randomly on this thread.

That said I'm still curious to know why you'd want to see the old style of that part of Tweetdeck, I still think it looks dated 😅

**Comment by AbuMaia** [comment]
Because I prefer having the definite background with boundary behind the image, instead of it floating in the middle of the screen.

What CSS options would I have to change to achieve this? This way I can do it myself and you won't have to care about it any.

**Comment by eramdam** [comment]
@AbuMaia Try this
```css
html .btd-loaded .overlay,
html .btd-loaded .ovl {
  background: rgba(56, 68, 77, 0.9) !important;
}
.med-fullpanel {
  background-color: #14171a !important;
  pointer-events: all !important;
  box-shadow: 0 0 10px rgba(20, 23, 26, 0.5) !important;
}

```
