### ISSUE TITLE
cann't customize column width

### ISSUE THREAD

**Issue by hy-zhao** [eramdam/BetterTweetDeck#586]
Here is my code for col width setting, but it doesn't work.
```
.js-column.column:nth-child(1) {
  table-layout: fixed;
  font-size: 14px;
  width: 100%;
  line-height: 1.8;
}
.js-column.column:nth-child(2) {
  font-size: 14px;
  width: 50%;
  line-height: 1.8;
}
.js-column.column:nth-child(3) {
  font-size: 14px;
  column-width: 50%;
  line-height: 1.8;
}
```

**Comment by eramdam** [comment]
@hy-zhao it works on my end, here's the correct snippet

```css
.js-column.column:nth-child(1) {
  font-size: 14px;
  width: 100%;
  line-height: 1.8;
}
.js-column.column:nth-child(2) {
  font-size: 14px;
  width: 50%;
  line-height: 1.8;
}
.js-column.column:nth-child(3) {
  font-size: 14px;
  width: 50%;
  line-height: 1.8;
}
```
