### ISSUE TITLE
Add an option to bring back the old (Rosetta) icons

### ISSUE THREAD

**Issue by Diyamund** [eramdam/BetterTweetDeck#635]
**Is your feature request related to a problem? Please describe.**
Many people [including me] don't like the new Twitter icons.

**Describe the solution you'd like**
I'd like an option that adds back the old icons.

**Describe alternatives you've considered**
I haven't though of any alternative solutions.

**Additional context**
You can use this CSS to bring back the old icons.

```css
@font-face {
    font-family: tweetdeckregular;
    src: url("https://abs.twimg.com/a/1462524371/font/rosetta-icons-Regular.woff");
}

.icon-heart-filled::before {
    content: "\F148"!important;
}

.icon-retweet-filled::before {
    content: "\F152"!important;
}
```

P.S.: The star icon option uses the new styled icon, so you'll have to fix that.

Example screenshot:

![image](https://user-images.githubusercontent.com/44238627/121760786-19485800-caf2-11eb-8fc1-5fc7631fde6b.png)
