### ISSUE TITLE
[Feature Request] Flash column when updated

### ISSUE THREAD

**Issue by viksra** [eramdam/BetterTweetDeck#654]
I don't always have sound turned on, so it would be nice if we could enable an option for a column to "flash" when it is updated with a new tweet. Perhaps even with a nice gradual 0.5s fade-out effect back to normal colors after it has flashed. Maybe it can get even more sophisticated by flashing a specific color IF the latest tweet within that column contains a certain keyword. ie: have a column added for the hashtag #test and flash blue whenever someone tweets the word "bob", otherwise flash green if someone in the #test column tweets the word "joe"

**Comment by eramdam** [comment]
It's funny because v3 used to have exactly this 😁 However I removed it in v4 because not a lot of people seemed to care and I found it distracting.

I feel like you should be able to replicate the effect with this bit of Custom CSS

```css
@keyframes tweetEnter {
  from {
    background-color: rgba(54, 82, 122, 1);
  }

  to {
    background-color: rgba(54, 82, 122, 0);
  }
}

/* Flashes new tweets in notifications/mention columns */
html.btd-loaded :matches(.column-type-interactions, .column-type-mention)
.js-chirp-container
> article:first-of-type {
  animation-duration: 2s;
    animation-name: tweetEnter;
}

/* Flashes new tweets in all types of columns */
html.btd-loaded [class*="column-type"]
.js-chirp-container
> article:first-of-type {
  animation-duration: 2s;
  animation-name: tweetEnter;
}
```
