### ISSUE TITLE
Reading improvement...

### ISSUE THREAD

**Issue by ClaudioEnriqueRossi** [eramdam/BetterTweetDeck#673]
It would be interesting if an option were added to make the texts justifiable, such as columns in newspapers.

**Comment by eramdam** [comment]
You _could_ maybe do it by applying a custom CSS like this one

```css
.js-tweet-text.tweet-text.with-linebreaks {
text-align: justify !important;
}
```

However, I feel like this won't work well and it will definitely have some weird effects on tweets in RTL languages. Feel free to mess around with the custom CSS feature to achieve that, but I'm not building this into an actual feature.
